-- MySQL Script generated by MySQL Workbench
-- 10/30/17 23:20:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Online_Test
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT NOT NULL,
  `course_name` VARCHAR(255) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `course_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `question_description` VARCHAR(255) NULL,
  PRIMARY KEY (`course_id`, `question_id`),
  INDEX `fk_question_course_idx` (`course_id` ASC),
  CONSTRAINT `fk_question_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  `mail_address` VARCHAR(255) NULL,
  `type` ENUM('s', 't', 'a') NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `exam_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `question_number` INT NULL,
  `question_score` INT NULL,
  PRIMARY KEY (`exam_id`, `course_id`),
  INDEX `fk_Exam_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_Exam_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer_available`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer_available` (
  `question_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `answer_available` VARCHAR(255) NULL,
  `is_correct` TINYINT(1) NULL,
  PRIMARY KEY (`question_id`, `answer_id`),
  INDEX `fk_answer_available_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_answer_available_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_teacher` (
  `course_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `teacher_id`),
  INDEX `fk_course_has_teacher_course1_idx` (`course_id` ASC),
  INDEX `fk_course_teacher_user1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_course_has_teacher_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_teacher_user1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_paper` (
  `exam_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`, `student_id`),
  INDEX `fk_test_paper_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_test_paper_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_paper_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question_choosed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question_choosed` (
  `exam_id` INT ZEROFILL NOT NULL,
  `student_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`, `student_id`, `question_id`),
  INDEX `fk_question_choosed_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_choosed_test_paper1`
    FOREIGN KEY (`exam_id` , `student_id`)
    REFERENCES `mydb`.`test_paper` (`exam_id` , `student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_choosed_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer_on_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer_on_paper` (
  `answer_id` INT NOT NULL,
  `exam_id` INT ZEROFILL NOT NULL,
  `student_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`answer_id`, `exam_id`, `student_id`, `question_id`),
  INDEX `fk_answer_on_paper_answer_available1_idx` (`answer_id` ASC),
  INDEX `fk_answer_on_paper_question_choosed1_idx` (`exam_id` ASC, `student_id` ASC, `question_id` ASC),
  CONSTRAINT `fk_answer_on_paper_answer_available1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `mydb`.`answer_available` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_on_paper_question_choosed1`
    FOREIGN KEY (`exam_id` , `student_id` , `question_id`)
    REFERENCES `mydb`.`question_choosed` (`exam_id` , `student_id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer_choosed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer_choosed` (
  `exam_id` INT ZEROFILL NOT NULL,
  `student_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`, `student_id`, `question_id`, `answer_id`),
  INDEX `fk_answer_choosed_question_choosed1_idx` (`exam_id` ASC, `student_id` ASC, `question_id` ASC),
  INDEX `fk_answer_choosed_answer_available1_idx` (`answer_id` ASC),
  CONSTRAINT `fk_answer_choosed_question_choosed1`
    FOREIGN KEY (`exam_id` , `student_id` , `question_id`)
    REFERENCES `mydb`.`question_choosed` (`exam_id` , `student_id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_choosed_answer_available1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `mydb`.`answer_available` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
