-- MySQL Script generated by MySQL Workbench
-- 10/29/17 23:29:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Online_Test
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT NOT NULL,
  `course_name` VARCHAR(255) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `course_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `question_description` VARCHAR(255) NULL,
  PRIMARY KEY (`course_id`, `question_id`),
  INDEX `fk_question_course_idx` (`course_id` ASC),
  CONSTRAINT `fk_question_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  `student_name` VARCHAR(255) NULL,
  `student_sex` ENUM('M', 'F') NULL,
  `student_class` INT NULL,
  `mail_address` VARCHAR(255) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `exam_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `question_number` INT NULL,
  `question_score` INT NULL,
  PRIMARY KEY (`exam_id`, `course_id`),
  INDEX `fk_Exam_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_Exam_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `teacher_id` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer_available`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer_available` (
  `course_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer_available` VARCHAR(255) NULL,
  `is_correct` TINYINT(1) NULL,
  PRIMARY KEY (`course_id`, `question_id`),
  CONSTRAINT `fk_answer_option_question1`
    FOREIGN KEY (`course_id` , `question_id`)
    REFERENCES `mydb`.`question` (`course_id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_teacher` (
  `course_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `teacher_id`),
  INDEX `fk_course_has_teacher_teacher1_idx` (`teacher_id` ASC),
  INDEX `fk_course_has_teacher_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_course_has_teacher_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_has_teacher_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_paper` (
  `exam_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`, `course_id`, `student_id`),
  INDEX `fk_test_paper_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_test_paper_exam1`
    FOREIGN KEY (`exam_id` , `course_id`)
    REFERENCES `mydb`.`exam` (`exam_id` , `course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_paper_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question_choosed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question_choosed` (
  `exam_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`, `course_id`, `student_id`, `question_id`),
  CONSTRAINT `fk_question_choosed_test_paper1`
    FOREIGN KEY (`exam_id` , `course_id` , `student_id`)
    REFERENCES `mydb`.`test_paper` (`exam_id` , `course_id` , `student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer_on_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer_on_paper` (
  `exam_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer_available` VARCHAR(255) NULL,
  PRIMARY KEY (`exam_id`, `course_id`, `student_id`, `question_id`),
  CONSTRAINT `fk_answer_on_paper_question_choosed1`
    FOREIGN KEY (`exam_id` , `course_id` , `student_id` , `question_id`)
    REFERENCES `mydb`.`question_choosed` (`exam_id` , `course_id` , `student_id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer_choosed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer_choosed` (
  `exam_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer_choosed` VARCHAR(255) NULL,
  PRIMARY KEY (`exam_id`, `course_id`, `student_id`, `question_id`),
  CONSTRAINT `fk_answer_choosed_question_choosed1`
    FOREIGN KEY (`exam_id` , `course_id` , `student_id` , `question_id`)
    REFERENCES `mydb`.`question_choosed` (`exam_id` , `course_id` , `student_id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
